### ISSUE TITLE
Catalog Server error code should be 400 based on user error handling, not 500

### ISSUE THREAD

**Issue by cyyeh** [Canner/vulcan-sql#212]
## Environment

- Version:
  

  ```
  cli version: 0.5.3
  core version: 0.5.3
  build version: 0.5.3
  serve version: 0.5.3
  ```

- OS: macOS using m1 chip
- Node: v16.20.0

## What's wrong?

I've created some user error handling code on SQL template, but the error code shown on Catalog Server UI page is 500.

```sql
{% set group_by = context.params.group_by %}

{% if group_by and group_by != "WHO_region" and group_by != "Country_code" %}
    {% error "group_by should be WHO_region or Country_code" %}
{% endif %}
```

## What's the correct behavior?

It should be 400 based on [documentation](https://vulcansql.com/docs/develop/error). At the moment, the terminal shows error code 400.
![image](https://github.com/Canner/vulcan-sql/assets/11023068/9d416c01-fcd7-49cf-a279-c81be3bd16e5)
![image](https://github.com/Canner/vulcan-sql/assets/11023068/33437749-832c-449b-b169-5852c8597a17)
![image](https://github.com/Canner/vulcan-sql/assets/11023068/24e43ee1-0756-49bc-bc97-fa07d8ec8047)

## Reproducing steps

- setup an api that makes users enter wrong parameter value.

**Comment by andreashimin** [comment]
Hi @cyyeh 

Because of GraphQL design reason, the status code in the network could not same as REST API.
reference link:
https://www.apollographql.com/docs/apollo-server/data/errors/#setting-http-status-code-and-headers

The adjustment will display a message including the status code, error code, and error message to the client,
 for example:

<img width="1339" alt="image" src="https://github.com/Canner/vulcan-sql/assets/9657305/f8a383cf-1144-449e-9a7c-a5e4cd4fbfbd">

You can check it at #206, Thanks.
